### ISSUE TITLE
Retrieving the mesh of an object by its semantic class

### ISSUE THREAD

**Issue by juntuck** [ethz-asl/voxblox-plusplus#102]
Hello there,

firstly thank you for sharing this amazing work! :)

I would like to semantically build an online map and selectively retrieve objects meshes for manipulation tasks. How can one retrieve the meshes / TSDF of individual objects according to their semantic class? Is there an API for this?

**Comment by margaritaG** [comment]
@juntuck 

While there's not specific API/service for retrieving a single object according do its semantic class, there are two other solutions to this:
- You can query for the list of all semantic instances in the map, and then query the aligned bounding box of an object given its instance ID (https://github.com/ethz-asl/voxblox-plusplus/pull/61). Pairing the bounding box and the generated scene mesh (`generate_mesh` service) will yield a portion of the mesh that contains the object you are interested in. Of course, there will be other objects within that bounding box too, so if you want exclusively that single object, go with option 2
- Use the `get_map` service (https://github.com/ethz-asl/voxblox-plusplus/wiki/The-voxblox-plusplus-node#services) and then filter the map based on the semantic class you are interested in to extract the target object TSDF.

**Comment by QuantumY-CHN** [comment]
Hi, I'm working on a similar problem. But after I enable the semantic instance segmentation, the label_instance_count_ in SemanticInstanceLabelFusion class keeps empty so that the SemanticInstanceLabelFusion::getInstanceLabel cannot correctly map the label to an instance label. Could you please hint to me where my problem is? I really appreciate any help you can provide.
