### ISSUE TITLE
Buffer Overrun error when calling the generate_mesh service

### ISSUE THREAD

**Issue by vincentcartillier** [ethz-asl/voxblox-plusplus#88]
Hi,

When calling the generate_mesh service I am getting the following error:

`[ERROR] [1597758013.424265642]: Exception thrown while processing service call: Buffer Overrun`

The error doesn't appear right away.
The system seems to crash after some compute is done. I've checked my RAM and and memory capacity is far from reached. 

Any ideas on how to overcome this?

System info:
- Ubuntu 16.04
- Ros-kinetic
- cuda-8.0
- tensorflow-gpu==1.3.0
- keras==2.0.8

**Comment by margaritaG** [comment]
@vincentcartillier 

I cannot reproduce your error, unfortunately. Two things come to mind, though.
The error might not only be RAM related, but 
- disk space (since the service exports the mesh a PLY file to disk, if the `meshing/mesh_filename` parameter is set) 
- or message serialization (since the service also publishes to the `/mesh` topic if the `publishers/publish_scene_mesh` parameter is set to `true`) 

related (further details in the [wiki](https://github.com/ethz-asl/voxblox-plusplus/wiki/The-voxblox-plusplus-node#services)). 

Try disabling both of the features I mentioned by un-setting the corresponding parameters, and see if the error persists.
